# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-16.04
    if: github.ref == 'refs/heads/main'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: ${{ secrets.DEPLOY_DIR }}
  env_file:
    name: Create Env file
    needs: [ deploy ]
    runs-on: ubuntu-16.04
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            rm .env
            echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} > .env
            echo PORT=${{ secrets.PORT }} >> .env
            echo DIR_UPLOAD=${{ secrets.DIR_UPLOAD }} >> .env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

            echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> .env
            echo EMAIL_PORT=${{ secrets.EMAIL_PORT }} >> .env
            echo EMAIL_USER=${{ secrets.EMAIL_USER }} >> .env
            echo EMAIL_PASS=${{ secrets.EMAIL_PASS }} >> .env
            echo EMAIL_FROM=${{ secrets.EMAIL_FROM }} >> .env
            npm install
